### PR TITLE
GFORMS-1418 Output summary & acknowledgement pdfs using Gform pdf gen…

### PR DESCRIPTION
**Pull request by girishkamat**
…erator

### CODE REVIEW

**Comment by josef-vlach** [comment]
Shouldn't we now remove this check:  https://github.com/hmrc/gform/blob/master/app/uk/gov/hmrc/gform/form/FormService.scala#L125-L128

**Comment by girishkamat** [comment]
> Shouldn't we now remove this check: https://github.com/hmrc/gform/blob/master/app/uk/gov/hmrc/gform/form/FormService.scala#L125-L128

No longer needed i guess. But we still have printPDF and notification PDF that rely on PDF generator. Do you know where they are used?

**Comment by josef-vlach** [comment]
printPDF and notificationPDF should be converted as well, so we can move away from PDF generator microservice completely.

For usage  look at `"printSection"` in our templates.

**Review by josef-vlach — APPROVED** [review]
Cannot we now remove that

**Pull request merged**
